namespace TestComponent
{
    struct ProcessResult {
        Boolean DidCreateSuccessfully;
        UInt64 ExitCode;
    };

    static runtimeclass ProcessRunner
    {
        static ProcessResult CallFileHandlingApp(String inputFilePath, String outputFileName);
    }
}
